[workspace]
authors = ["Uspfe"]
channels = ["conda-forge"]
name = "issac_sim_eval"
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
python = "3.11.*"

[system-requirements]
libc="2.35"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://pypi.nvidia.com"]

[activation.env]
# use isaac sim's internal minimal ros installation (see https://docs.isaacsim.omniverse.nvidia.com/5.1.0/installation/install_ros.html)
isaac_sim_package_path = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/python3.11/site-packages/isaacsim"
ROS_DISTRO = "humble"
LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$isaac_sim_package_path/exts/isaacsim.ros2.bridge/humble/lib"

[environments]
default = {features = [], solve-group = "default"}

[pypi-dependencies]
isaacsim = { version = "==5.1.0", extras = ["all", "extscache", "ros2"] }
numpy = "*"
scipy = "*"
matplotlib = "*"
